### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by neworderofjamie** [BrainsOnBoard/bob_robotics#10]
I think one thing this (and GeNN) would benefit from is a proper logging library (**ideally** the same one :smile:) - the current choice between `#ifdef``, ``std::cout`` and ``std::cerr`` is often irritating. Requirements we need:

- Lightweight - not one of those hardcore enterprisey logging libraries where you can log to some insane hierachy of system event logs, files that get swapped out every 7 minutes etc etc.
- Easy to build - ideally header only
- Thread-safe
- Works on Windows, Linux and Mac
- Liberal licence
- A stream-based interface - A lot of the code in both projects uses streams and this will make for an easier swapping out of ``std::cout`` and ``std::cerr``.
- Multiple logging streams e.g. the verbosity of GeNN messages can be controlled independently of the verbosity of GeNNRobotics messages
- Gives the impression of being reasonably well maintained

After scouring the internet I've come up with a shortlist that fits this bill:

- https://github.com/muflihun/easyloggingpp - it's a **little** bit on the heavyweight side, requires linking a cc rather than just a header, but otherwise looks pretty nice
- https://github.com/SergiusTheBest/plog - header only, real small 
- https://github.com/emilk/loguru - header only and looks cool **but** there's a lot of preprocessor magic that, as far as I can tell, dumps an implementation blob of code in one of your implementation files which would make it a pain for e.g. applications combining GeNN with GeNN robotics stuff.

On this basis and, unless @alexdewar happens to know of another logging library I couldn't locate, I'm tempted to try out plog

**Comment by alexdewar** [comment]
I think plog looks great. I'd also prefer to have just a header file in the repo than mess around with linking or downloading extra bits on Windows.

**Comment by neworderofjamie** [comment]
Ok cool - I will have a go at integrating plog
