### ISSUE TITLE
Use a better, platform-independent build system

### ISSUE THREAD

**Issue by alexdewar** [BrainsOnBoard/bob_robotics#104]
Our current build system is essentially based on GNU makefiles. Although nominally we support Windows, most of the examples are not in the provided VS solution and it is annoying to constantly have to manually add and edit new VS projects for every tool and example we provide. In addition, makefiles do have some other limitations (e.g. annoying syntax + .PHONY targets force a rebuild every time make is run).

It would probably be better to use something like cmake (though I suppose there are other options such as meson). This would make it easier to make platform-independent BoB robotics programs and would also help with e.g. CI testing on Windows.

**Comment by neworderofjamie** [comment]
cmake is becoming 'almost native' in Visual Studio so I think it would be the sensible choice

**Comment by alexdewar** [comment]
Yeah I agree. I might have a look at this soon....

**Comment by neworderofjamie** [comment]
My only comment would be that a lot of the stuff makes no sense on Windows so it may not be worth it

**Comment by alexdewar** [comment]
That is true, but I feel cmake might be a better option than recursive makefiles even for the Linux-y code. I'll have a play and see if it makes sense

⁣Sent from BlueMail ​

**Comment by neworderofjamie** [comment]
Fixed by #107
