### ISSUE TITLE
cv::waitKeyEx is even less platform-independant than you thought...

### ISSUE THREAD

**Issue by neworderofjamie** [BrainsOnBoard/bob_robotics#12]
unwrapconfig works on QT based OpenCV but, on GTK based OpenCV (for some reason the version of OpenCV on robot is), it would seem the keycodes returned by ``cv::waitKeyEx`` are different. Experimentally it would seem that the current code works if you ``switch(key & 0xFFFF)`` at line 105 but that will definitely break windows key codes so maybe ``OS::KeyCodes`` should include a per-platform mask or something as well....

**Comment by alexdewar** [comment]
Hmm how strange... I remember having similar problems with `cv::waitKeyEx` in the past where the higher-order bits were also encoding whether caps lock was enabled etc. We should be able to get round this as you suggest though.

**Comment by neworderofjamie** [comment]
pretty sure this is fixed now

**Comment by alexdewar** [comment]
Yep it is.
