### ISSUE TITLE
AntWorld: Junk in frames read from non-NVIDIA GPUs

### ISSUE THREAD

**Issue by alexdewar** [BrainsOnBoard/bob_robotics#188]
When reading a frame with one of the helper functions, the first frame read often (always?) seems to contain junk (e.g. a picture of whatever is behind): https://github.com/BrainsOnBoard/ant_world_image_databases/blob/master/databases/high_res/routes/ant1_route1/image_00000.png

I'm not sure if this is due to us reading from the front buffer, or something?

**Comment by neworderofjamie** [comment]
I think this is just an order issue - ``Camera::readFrame `` calls:
-  ``Camera::update`` which renders and then flips the buffers 
- ``OpenGL::readFrame`` which reads the now invalid buffer

The flipping just needs to happen after the reading

**Comment by alexdewar** [comment]
That seemed to do the trick. Thanks!
