### ISSUE TITLE
Build issues with CMake < 3.13

### ISSUE THREAD

**Issue by alexdewar** [BrainsOnBoard/bob_robotics#204]
This affects Ubuntu 18.04 and older. Annoyingly this includes the current version of the NVIDIA JetPack for Jetsons. On macOS you can get a newer version of CMake from homebrew, but you have to make sure that it is on your path, otherwise you may be using an outdated version.

Issues:
- The OpenCV cmake package forces the C++ standard to be C++11 with older versions of CMake, which breaks all the C++14 code we have
- At some point I apparently broke the linking process for older versions of CMake, so you get linking errors with e.g. OpenCV

Workaround:
- Install a newer version of CMake

You can either build from source or use Kitware's APT repository: https://apt.kitware.com/
(though I doubt they provide builds for ARM64)

**Comment by neworderofjamie** [comment]
When did this break? I was building BoB robotics on a Jetson with one of the Ubuntu 16.04 Jetpacks the other day? Is this maybe only an issue with newer OpenCVs (I suspect this had 3.something)

**Comment by alexdewar** [comment]
I've done some more probing and I think it might be. Maybe I'll submit an issue upstream if I can figure out exactly what the problem is.

**Comment by neworderofjamie** [comment]
Found another delightful cmake issue on Ubuntu 16.0.4:
```cmake
if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.13.0")
```
The ``VERSION_GREATER_EQUAL`` operator isn't supported by cmake < 3.7.2 so maybe this needs turning into a VERSION GREATER "3.12.9" or however cmake versions work...
