### ISSUE TITLE
[Documentation] Links under "Example image database" Broken

### ISSUE THREAD

**Issue by nitik1998** [BrainsOnBoard/bob_robotics#218]
The links redirecting to ```ImageDatabase``` and ```ant_world_db_creator``` on the fuller documentation [page](https://brainsonboard.github.io/bob_robotics/), under the tab "Example image database" are broken and throw up a 404 Error.  The link to the page is [this](https://brainsonboard.github.io/bob_robotics/md_docs_source_example_image_databases_README.html).

**Comment by alexdewar** [comment]
Good spot. Thanks!
