### ISSUE TITLE
Build issues with OpenCV > 4.2.0 on Ubuntu 18

### ISSUE THREAD

**Issue by neworderofjamie** [BrainsOnBoard/bob_robotics#265]
4.2.0 works fine but, something deep in the build system for subsequent versions overrides the C++ standard and breaks builds with cmake <= 3.10.2. Based on a diff of the cmake directories of cmake 4.2.0 and 4.30 I would be particularly suspicious of this change in OpenCVConfig.cmake.in:

```cmake
# Require C++11 features for OpenCV modules
if(CMAKE_VERSION VERSION_LESS "3.1")
  if(NOT OpenCV_FIND_QUIETLY AND NOT OPENCV_HIDE_WARNING_COMPILE_FEATURES)
    message(STATUS "OpenCV: CMake version is low (${CMAKE_VERSION}, required 3.1+). Can't enable C++11 features: https://github.com/opencv/opencv/issues/13000")
  endif()
else()
  set(__target opencv_core)
  if(TARGET opencv_world)
    set(__target opencv_world)
  endif()
  set(__compile_features cxx_std_11)  # CMake 3.8+
  if(DEFINED OPENCV_COMPILE_FEATURES)
    set(__compile_features ${OPENCV_COMPILE_FEATURES})  # custom override
  elseif(CMAKE_VERSION VERSION_LESS "3.8")
    set(__compile_features cxx_auto_type cxx_rvalue_references cxx_lambdas)
  endif()
  if(__compile_features)
    # Simulate exported result of target_compile_features(opencv_core PUBLIC ...)
    set_target_properties(${__target} PROPERTIES
        INTERFACE_COMPILE_FEATURES "${__compile_features}"
    )
  endif()
  unset(__target)
  unset(__compile_features)
endif()
```
which was added just after the 4.2.0 release (https://github.com/opencv/opencv/commit/01c1b341a881ba49d538acdf29d49ca7fd8ada57#diff-452ddb3443d10f7a9d257cfa21a76135a63c36ebcf21ed8355531dd627ff2329). I can also confirm, if I insert that code into a working OpenCV 4.2.0 installation's OpenCVConfig.cmake, it breaks.

**Comment by neworderofjamie** [comment]
Setting ``OPENCV_COMPILE_FEATURES`` to "" seems to be a good workaround, maybe this could be integrated into the BoB cmake world?

**Comment by alexdewar** [comment]
I've put in a PR, but I guess if this is def an upstream issue we should also probs open an issue there too...?
