### ISSUE TITLE
CorrCoefficient is over 50x slower than AbsDiff

### ISSUE THREAD

**Issue by neworderofjamie** [BrainsOnBoard/bob_robotics#268]
This is on my new workstation with a 16 thread Xeon with 24Mb cache so, I fear, this is going to be too slow for robot use even with windowing. Talking to Stathis and looking at the code that eventually gets called in our situation (https://github.com/opencv/opencv/blob/170bf6d7af9c8bb2b34ec143826594dc84251b89/modules/imgproc/src/templmatch.cpp#L566-L760), it appears that ``cv::templateMatch`` is, as the name suggests, more general and capable of handling different sized input images through some complex DFT based tiled thing. Whereas, Stathis's code does the following:
```python
def nan_correlation_dist(a, b):
    """
    Calculates the correlation coefficient distance
    between two vectors.
    Where a and b can contain nan values.
    :param a:
    :param b:
    :return:
    """
    amu = np.nanmean(a)
    bmu = np.nanmean(b)
    a = a - amu
    b = b - bmu
    ab = np.nanmean(a * b)
    avar = np.nanmean(np.square(a))
    bvar = np.nanmean(np.square(b))
    dist = 1.0 - ab / np.sqrt(avar * bvar)
    return dist
```
and, as you would guess from looking at it, it is only around 5x slower than AbsDiff. I think we could massively optimise ``CorrCoefficient`` by implementing it directly using lower-level integer OpenCV ops.

**Comment by alexdewar** [comment]
After testing it on my machine I have confirmed that performance is godawful (on my machine it's actually >100x slower)... not sure how this escaped my notice before.

**Comment by alexdewar** [comment]
There is also the problem that ``cv::templateMatch`` had a bug until very recently so our current code doesn't support using image masks with ``CorrCoefficient`` except for super-new versions of OpenCV in any case.

**Comment by neworderofjamie** [comment]
Yeah, I was measuring times using ``time`` which suggested that all my cores were contributing to the mere 50x slowdown :)Having foolishly disturbed the (clearly very delicate) vcpkg status quo on my Windows machine, trying to get super new OpenCV I can agree that that is also a definite downside 😄

**Comment by tnowotny** [comment]
out of curiosity, which software is used for the image differencing and for the correlation calculation in each case?

**Comment by alexdewar** [comment]
You mean in @efkag's code vs mine...?

**Comment by tnowotny** [comment]
I was thinking about on either side of the 50X slow-down.

**Comment by neworderofjamie** [comment]
the 50x slow-down is between ``cv::absDiff`` and ``cv::templateMatch``, both C++ OpenCV methods implemented but, if you follow my link into the source, you'll see why cv::templateMatch is likely to be pretty slow

**Comment by alexdewar** [comment]
Yep! But as @neworderofjamie pointed out, the builtin ``cv::templateMatch()`` method probably isn't the right tool for the job here. It's too general

**Comment by tnowotny** [comment]
Tried to read the code but seems *very* convoluted for calculating a correlation. Are they calculating a discrete Fourier transform to make this a differencing operation in Fourier space?!?!
Also was confused about blocksize calculation ... this isn't using CUDA, or is it?

**Comment by neworderofjamie** [comment]
Yeah so, my reading is that their code is intended for finding the correlation peak when you 'slide' a smaller image over a larger one. Presumably with typical image sizes for those applications, Fourier space makes sense 🤷

**Comment by tnowotny** [comment]
One more thought on this: Stathis' implementation makes a lot of sense but if you do a multi-comparison of differently rotated examples, then 90% of the work is the same for each of the calls to this function; so one could make that a lot more efficient.

**Comment by tnowotny** [comment]
To be more specific:
```python
ab = np.nanmean(a * b)
```
is the only operation that depends on relative rotation.

**Comment by neworderofjamie** [comment]
That is indeed true! However, in the C++ code, beyond the question of bending the abstraction to take that into account, I believe the loops around rotations are auto-parallelised which will add further issues...

**Comment by neworderofjamie** [comment]
@alexdewar the differencer is a already a template parameter for the

**Comment by alexdewar** [comment]
Very true! I'm sure there will be some way to wrangle it... I'll have a play with things.

For now I'll just knock up a naive implementation though and see how that performs. (Hopefully better than 2 orders of magnititude slower!)

**Comment by alexdewar** [comment]
> Tried to read the code but seems _very_ convoluted for calculating a correlation. Are they calculating a discrete Fourier transform to make this a differencing operation in Fourier space?!?!
> Also was confused about blocksize calculation ... this isn't using CUDA, or is it?

And yes OpenCV *can* use CUDA (or OpenCL!) if it's built with the right options and the libraries are available at runtime, hence why some of the methods in OpenCV can end up being so convoluted!

**Comment by tnowotny** [comment]
> Although....@alexdewar the differencer is already a template parameter to `Navigation::RawImage` so it wouldn't be _that_ difficult to replace the `std::pair` of image and mask, stored in `Navigation::RawImage::m_Snapshots` with a tuple with image, mask and other elements desired by the differencer - in this case `|img|` and `|img*img|` 😈 would only be 3 more bytes per snapshot

... and hence those would only be computed once in the lifetime of the entire memory ... during exploration/learning.

**Comment by alexdewar** [comment]
Yeah. I've had a vague idea for a while that we could abstract away these preprocessing steps in some way. We're doing the same thing with the HOG version of perfect memory and DCT hashes (i.e. processing the snapshots and storing them pre-processed) and I feel like there has to be *some* way to make this generic.

**Comment by efkag** [comment]
Sorry, I just saw this today. 
Just to expand on @tnowotny's very good point. The mean and std.Dev. of each image is indeed rotation invariant.
A way to further reduce the number of operations would be to remove the mean of each image when stored or once received through the camera stream. Then the Corr. Coff computation becomes simply the cosine distance formula.
`def cos_dist(a, b):
    return 1.0 - np.dot(a, b) / (norm(a) * norm(b))`
    
Even further if we also divide each image by its std.Dev, thus normalizing each image, then a dot product calculation between image vectors is mathematically equivalent to the Corr.Coeff of unnormalized images.

The issue is that OpenCV expects image values to be in the range 0-255. So any normalization would have to take place after the OpenCV preprocessing steps.

**Comment by tnowotny** [comment]
very good points ... as for the last one: storing the mean and dividing by it every time isn't that much of a waste compared to recalculating it every time I would think.

**Comment by alexdewar** [comment]
@efkag This isn't top of my to-do list right now, so do let me know if you need it sorting urgently, or if you'd like help figuring out a fix yourself.
