### ISSUE TITLE
Phantom duplicate OpenCV libraries linked to Visual Studio project

### ISSUE THREAD

**Issue by neworderofjamie** [BrainsOnBoard/bob_robotics#276]
The project generated by cmake has two sets of Open CV libraries:
```
opencv_videoio.lib
opencv_video.lib
opencv_stitching.lib
opencv_photo.lib
opencv_objdetect.lib
opencv_ml.lib
opencv_imgproc.lib
opencv_imgcodecs.lib
opencv_highgui.lib
opencv_flann.lib
opencv_features2d.lib
opencv_dnn.lib
opencv_core.lib
opencv_calib3d.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_video.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_stitching.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_photo.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_objdetect.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_ml.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_highgui.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_videoio.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_imgcodecs.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_dnn.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_calib3d.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_features2d.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_imgproc.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_flann.lib
C:\Users\jamie\Documents\programming\vcpkg\installed\x64-windows\lib\opencv_core.lib
```
In order to build the project, you need to manually remove the first set. As a Visual Studio user, you wouldn't really expect full paths here. Typically you'd add the libraries by name and add the path they're in to the project's list of library directories...

**Comment by alexdewar** [comment]
Out of interest, what happens if you use the OpenCV package directly without all the BoB business?

Make a CMakeLists.txt file with this in:
```cmake
find_package(OpenCV REQUIRED)

foreach(LIB IN LISTS OpenCV_LIBS)
    message(STATUS ${LIB})
endforeach(LIB IN LISTS OpenCV_LIBS)
```

I suspect this will still yield the same result but I just want to double check that we're not just adding libraries twice ourselves somehow.

**Comment by neworderofjamie** [comment]
It doesn't find the package. I also tried adding the following crud from bob_robotics.cmake before the ``find_package`` and it **still** doesn't find the package so no idea tbh:

```cmake
set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "")
set(VCPKG_PACKAGE_DIR "$ENV{VCPKG_ROOT}/installed/${PLATFORM}")

# The vcpkg toolchain in theory should do something like this already, but
# if we don't do this, then cmake can't find any of vcpkg's packages
file(GLOB children "${VCPKG_PACKAGE_DIR}/share/*")
foreach(child IN LISTS children)
    if(IS_DIRECTORY "${child}")
        list(APPEND CMAKE_PREFIX_PATH "${child}")
    endif()
endforeach()

# Link against vcpkg packages' libs
link_directories("${VCPKG_PACKAGE_DIR}/lib")
```

**Comment by alexdewar** [comment]
Hmm weird. I'm taking a look at CMake stuff on Windows today anyway so I'll see if I can sort it.

In general though, CMake does use full paths to libraries, even shared libraries on Unix, because then it's explicitly linking against a particular file rather than relying on your library path being correct etc. In theory, you shouldn't need to manually edit your Visual Studio project as all this nonsense should be sorted out at the CMake stage.

**Comment by neworderofjamie** [comment]
Excellent - I feel it's decidedly possible that this and the python packaging issues might be cleared up by your de-hacking of the CMake!

Absolute paths do indeed make sense as a cross-platform default - Visual Studio best practise is a somewhat irrelevant goal when the projects are intended to be entirely managed by CMake.

**Comment by alexdewar** [comment]
Out of interest, do you still have the same issue if you use my ``bob_cmake_package`` branch (which has all my CMake tidying in)?

The display example compiles and runs ok for me with no additional hacking of project files needed.
