### ISSUE TITLE
snapshot_bot's cropping sometimes causes issues

### ISSUE THREAD

**Issue by alexdewar** [BrainsOnBoard/bob_robotics#279]
I've been tweaking the snapshot_bot (see #278) and I was just wondering whether we actually need to crop images? I'm not entirely sure what the main rationale was: is it to crop out more of the ceiling/floor or to test the algo with a reduced horizontal FOV? If it's the former, we could also just achieve that by changing the unwrapper parameters (inner circle and outer circle).

This did bite us once when @efkag collected a dataset for me and only the top left corner of images were saved: https://github.com/BrainsOnBoard/sussex-ftl-dataset/tree/master/test_runs/SLAM_test_route
(Presumably because the crop rectangle was smaller than the saved image size.)

I was just wondering whether we should strip this functionality out? We could also remove it in a backwards compatible way to ensure existing saved training routes don't break, but I'm not sure how important that is to you.

**Comment by neworderofjamie** [comment]
It's for cropping out ceilings and floors. I think it would be much better if the code saved uncropped snapshots and **then** cropped them so you could test the same datasets with different crops but, to me, cropping is a much more intuitive way of adjusting this than fiddling with camera unwrap parameters. It also lets you fiddle with FOV

**Comment by alexdewar** [comment]
So I think we're agreed after the meeting: leave the cropping in, but save raw unprocessed images as snapshots instead. I'll close this issue.
