### ISSUE TITLE
Horribly slow performance for training InfoMax networks

### ISSUE THREAD

**Issue by alexdewar** [BrainsOnBoard/bob_robotics#290]
Currently, training with an image of size 90x25 and 90x25 hidden units, it's taking around 10 secs *per image* to train. I've no idea when this problem started, but it seems to be present on both Arch and Ubuntu (running in docker). By contrast, the numpy-based implementation in navbench takes only around ~200 ms per image.

**Comment by alexdewar** [comment]
@neworderofjamie Have you tried running e.g. snapshot_bot with infomax any time recently? I tried rolling back to a fairly old commit (5cda094c7e4bb8252290892a5d0d54318e46fc02) and still had the same problem.

**Comment by neworderofjamie** [comment]
When I was doing it for the ALife paper I always trained the weights on my laptop because it was too slow on the Jetson but I can't really remember exactly how slow that was.....sorry

**Comment by neworderofjamie** [comment]
We should attempt to hook some sort of performance regression tracking Jenkins plugin to some of our tests (the one where the different PMs are compared and the InfoMax for example) so it's easier to find if and when we accidentally break performance

**Comment by alexdewar** [comment]
Found the culprit! It turned out CMake was building without optimisation :worried:

**Comment by alexdewar** [comment]
> We should attempt to hook some sort of performance regression tracking Jenkins plugin to some of our tests (the one where the different PMs are compared and the InfoMax for example) so it's easier to find if and when we accidentally break performance

Good idea. We def want to keep an eye on big performance regressions for e.g. if we accidentally disable parallelisation in a build.

**Comment by neworderofjamie** [comment]
Ouch! That can make a huge difference - with GeNN CPU builds, the right optimisation flags make the difference between auto-vectorizing and not which gives a speed-up of 4-8x depending on your CPU...
