### ISSUE TITLE
``snapshot_bot`` records pitch as roll and roll as pitch

### ISSUE THREAD

**Issue by alexdewar** [BrainsOnBoard/bob_robotics#309]
Reported by @FullAPVayne.

**Comment by alexdewar** [comment]
@FullAPVayne Am I right in thinking that the pitch and roll were actually the right way round when you and I were doing our test the other day? I know we weren't actually using the ``snapshot_bot`` program but it'd be good to figure out where the source of this error is.

**Comment by neworderofjamie** [comment]
With the IMU, which is which will depend on how it's mounted

**Comment by alexdewar** [comment]
Oh yeah... Duh! I forgot we were using a different robot last week. Let's just close this issue then and leave it up to @FullAPVayne and @efkag to make sure the IMU is the right way round before they do experiments :smile:
