### ISSUE TITLE
Fix build on Windows

### ISSUE THREAD

**Issue by alexdewar** [BrainsOnBoard/bob_robotics#332]
I fear the range library may not work properly on MSVC :cry:

**Comment by neworderofjamie** [comment]
Do you want me to test? I have VS2019 on my machine at home which is supposed to be C++17 compliant

**Comment by alexdewar** [comment]
Thanks, but I have been trying it myself with VS2019 and it's not working :cry:. Even setting the C++ standard to C++17 doesn't fix it (although it does actually work with C++11 on gcc).

I should probably open an issue. I don't think I'm the only one having problems though: https://github.com/ericniebler/range-v3/issues?q=is%3Aissue+is%3Aopen+msvc

**Comment by alexdewar** [comment]
It's kinda weird really. I had it in mind the ``ranges-v3`` library was a pretty standard one.

**Comment by neworderofjamie** [comment]
The docs say it needs:
> /permissive- and either /std:c++latest or /std:c++17

**Comment by alexdewar** [comment]
Sorted!
