### ISSUE TITLE
VICON module doesn't handle object loss

### ISSUE THREAD

**Issue by ajc158** [BrainsOnBoard/bob_robotics#79]
Occasionally the VICON system will drop an object. If this occurs the VICON module currently (from my reading of the code) would continue to pass on the old object position continuously. This is dangerous as the code using this data has no way of knowing that a dropout has occurred and handling it. Two options exist - reset all object data to zero before parsing a new VICON packet - thus the end code can detect zero and act accordingly. Conversely drop the object from the list when the VICON data drops out - this is obviously a larger fix, but has the benefit of being clearer to the end code - if an object no longer exists in the VICON class then it has suffered dropout.

**Comment by alexdewar** [comment]
I was hitting up against the same issue recently and I have a bit of a fix for it. I added a field to the ``ObjectData`` class that indicates how long ago the data was received, so e.g. you can stop your robot if its position hasn't been updated in 5s or so.

I can put in a PR for this if you think it would help with your use-case?

**Comment by neworderofjamie** [comment]
After a brief attempt to implement my first thought, I think what @alexdewar suggests is the best solution.
